# Generated by Django 4.2.7 on 2023-11-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenguages1',
            field=models.CharField(choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenguages2',
            field=models.CharField(choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_work',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stack',
            field=models.CharField(choices=[('1', 'Front-End'), ('2', 'Back-End'), ('3', 'Full-Stack')], max_length=20, null=True),
        ),
    ]
