# Generated by Django 4.2.7 on 2023-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_mail_user_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lenguages1',
            field=models.CharField(blank=True, choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lenguages2',
            field=models.CharField(blank=True, choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='open_work',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='user',
            name='stack',
            field=models.CharField(blank=True, choices=[('1', 'Front-End'), ('2', 'Back-End'), ('3', 'Full-Stack')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
