# Generated by Django 4.2.7 on 2023-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
