# Generated by Django 4.2.7 on 2023-11-23 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_friendlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=400)),
                ('lenguages1_project', models.CharField(blank=True, choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True)),
                ('lenguages2_project', models.CharField(blank=True, choices=[('1', 'Js'), ('2', 'Python'), ('3', 'Java'), ('4', 'Rust'), ('5', 'Go')], max_length=20, null=True)),
                ('project_url', models.URLField()),
                ('repo_url', models.URLField()),
                ('collaborators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friendlist')),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
